run:
  timeout: 2m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
